import { Octokit } from '@octokit/rest';
import { createHash } from 'crypto';

export type RepoRef = {
  owner: string;
  repo: string;
};

export type RepoSnapshot = {
  ref: RepoRef;
  htmlUrl: string;
  name: string;
  description: string | null;
  stars: number;
  forks: number;
  openIssues: number;
  language: string | null;
  topics: string[];
  defaultBranch: string;
  readme: string;
  issues: Array<{
    title: string;
    body: string | null;
    labels: string[];
    comments: number;
    url: string;
  }>;
};

export type CreatedIssue = {
  number: number;
  title: string;
  url: string;
};

export type GrowthTaskInput = {
  title: string;
  priority: 'High' | 'Medium' | 'Low';
  reason: string;
};

export type BulkIssueResult =
  | { title: string; status: 'created'; issue: CreatedIssue }
  | { title: string; status: 'skipped'; reason: string }
  | { title: string; status: 'failed'; error: string };

function octokit() {
  return new Octokit({ auth: process.env.GITHUB_TOKEN || undefined });
}

export function parseGitHubRepo(input: string): RepoRef {
  const trimmed = input.trim();
  const shorthand = trimmed.match(/^([A-Za-z0-9_.-]+)\/([A-Za-z0-9_.-]+)$/);
  if (shorthand) return { owner: shorthand[1], repo: shorthand[2].replace(/\.git$/, '') };

  const url = new URL(trimmed);
  if (!url.hostname.includes('github.com')) {
    throw new Error('Please provide a GitHub repository URL.');
  }

  const [owner, repo] = url.pathname.split('/').filter(Boolean);
  if (!owner || !repo) {
    throw new Error('GitHub URL must include owner and repository name.');
  }

  return { owner, repo: repo.replace(/\.git$/, '') };
}

export async function fetchRepoSnapshot(input: string): Promise<RepoSnapshot> {
  const ref = parseGitHubRepo(input);
  const client = octokit();

  const repoResponse = await client.repos.get({ owner: ref.owner, repo: ref.repo });
  const repo = repoResponse.data;
  if (repo.private) {
    throw new Error('Only public GitHub repositories are supported.');
  }

  let readme = '';
  try {
    const readmeResponse = await client.repos.getReadme({ owner: ref.owner, repo: ref.repo });
    if (!Array.isArray(readmeResponse.data) && 'content' in readmeResponse.data) {
      readme = Buffer.from(readmeResponse.data.content, 'base64').toString('utf8');
    }
  } catch {
    readme = repo.description || '';
  }

  let issues: RepoSnapshot['issues'] = [];
  try {
    const issueResponse = await client.issues.listForRepo({
      owner: ref.owner,
      repo: ref.repo,
      state: 'open',
      per_page: 12,
      sort: 'updated',
      direction: 'desc'
    });

    issues = issueResponse.data
      .filter((issue) => !issue.pull_request)
      .map((issue) => ({
        title: issue.title,
        body: issue.body ?? null,
        labels: issue.labels.map((label) => (typeof label === 'string' ? label : label.name || '')).filter(Boolean),
        comments: issue.comments,
        url: issue.html_url
      }));
  } catch {
    issues = [];
  }

  return {
    ref,
    htmlUrl: repo.html_url,
    name: repo.name,
    description: repo.description,
    stars: repo.stargazers_count,
    forks: repo.forks_count,
    openIssues: repo.open_issues_count,
    language: repo.language,
    topics: repo.topics || [],
    defaultBranch: repo.default_branch,
    readme,
    issues
  };
}

function growthIssueTitle(title: string) {
  return `[GlobalDev] ${title}`;
}

function growthIssueKey(input: { repoUrl: string; title: string; reason: string }) {
  return createHash('sha256').update(`${input.repoUrl}\n${input.title}\n${input.reason}`).digest('hex').slice(0, 16);
}

function buildGrowthIssueBody(input: { repoUrl: string; title: string; priority: 'High' | 'Medium' | 'Low'; reason: string }) {
  const key = growthIssueKey({ repoUrl: input.repoUrl, title: input.title, reason: input.reason });
  return [
    '## GlobalDev Agent Growth Task',
    '',
    `**Priority:** ${input.priority}`,
    '',
    '### Why this matters',
    input.reason,
    '',
    '### Suggested next step',
    '- Review this task with the product / DevRel owner.',
    '- Convert it into a concrete implementation or launch checklist item.',
    '',
    '---',
    `GlobalDev-Key: ${key}`,
    'Generated by GlobalDev Agent from the repository launch analysis workflow.'
  ].join('\n');
}

function extractGrowthKey(body: string | null | undefined) {
  if (!body) return null;
  const match = body.match(/GlobalDev-Key:\s*([a-f0-9]+)/i);
  return match?.[1] ?? null;
}

function sleep(ms: number) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

export async function createGrowthIssue(input: { repoUrl: string } & GrowthTaskInput): Promise<CreatedIssue> {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error('GITHUB_TOKEN is not configured. Add it to Vercel Environment Variables with Issues write permission.');
  }

  const ref = parseGitHubRepo(input.repoUrl);
  const client = octokit();
  const body = buildGrowthIssueBody(input);

  const response = await client.issues.create({
    owner: ref.owner,
    repo: ref.repo,
    title: growthIssueTitle(input.title),
    body,
    labels: ['globaldev-agent', 'growth']
  });

  return {
    number: response.data.number,
    title: response.data.title,
    url: response.data.html_url
  };
}

export async function createGrowthIssuesBulk(input: { repoUrl: string; tasks: GrowthTaskInput[] }): Promise<BulkIssueResult[]> {
  if (!process.env.GITHUB_TOKEN) {
    throw new Error('GITHUB_TOKEN is not configured. Add it to Vercel Environment Variables with Issues write permission.');
  }

  const ref = parseGitHubRepo(input.repoUrl);
  const client = octokit();

  const existing = await client.issues.listForRepo({
    owner: ref.owner,
    repo: ref.repo,
    state: 'all',
    labels: 'globaldev-agent',
    per_page: 100,
    sort: 'updated',
    direction: 'desc'
  });

  const existingKeys = new Set<string>();
  const existingTitles = new Set<string>();

  for (const issue of existing.data) {
    if (issue.pull_request) continue;
    const key = extractGrowthKey(issue.body);
    if (key) existingKeys.add(key);
    existingTitles.add(issue.title.trim().toLowerCase());
    existingTitles.add(issue.title.replace(/^\[GlobalDev\]\s*/i, '').trim().toLowerCase());
  }

  const results: BulkIssueResult[] = [];

  for (const task of input.tasks) {
    const title = growthIssueTitle(task.title);
    const key = growthIssueKey({ repoUrl: input.repoUrl, title: task.title, reason: task.reason });

    if (existingKeys.has(key) || existingTitles.has(title.trim().toLowerCase()) || existingTitles.has(task.title.trim().toLowerCase())) {
      results.push({ title: task.title, status: 'skipped', reason: 'Already exists' });
      continue;
    }

    try {
      const body = buildGrowthIssueBody({ repoUrl: input.repoUrl, ...task });
      const response = await client.issues.create({
        owner: ref.owner,
        repo: ref.repo,
        title,
        body,
        labels: ['globaldev-agent', 'growth']
      });

      const created: CreatedIssue = {
        number: response.data.number,
        title: response.data.title,
        url: response.data.html_url
      };

      results.push({ title: task.title, status: 'created', issue: created });
      existingKeys.add(key);
      existingTitles.add(title.trim().toLowerCase());
      await sleep(250);
    } catch (error) {
      const message = error instanceof Error ? error.message : 'Failed to create issue';
      results.push({ title: task.title, status: 'failed', error: message });
    }
  }

  return results;
}
